services:
  rabbitmq:
    container_name: rabbitmq
    image: rabbitmq:4-management
    ports:
      - '5672:5672'  # Porta para acessar o RabbitMQ
      - '15672:15672' # Porta para acessar o painel de controle
    environment:
        RABBITMQ_DEFAULT_USER: rabbitmq
        RABBITMQ_DEFAULT_PASS: rabbitmq
    networks:
        - aschade-network
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq  # Persistência de dados
      - rabbitmq_logs:/var/log/rabbitmq  # Logs do RabbitMQ

volumes:
    rabbitmq_data:
    rabbitmq_logs:

networks:
  aschade-network:
    driver: bridge
