export interface Product {
    id: number;
    brand: string;
    title: string;
    description: string;
    price: number;
    image: string;
    category: string;
}

export const products: Product[] = [
    {
        id: 1,
        brand: "ADIDAS",
        title: "Raquete De Beach Tennis adidas Bt 3.0 Rosa/amarelo",
        description: "Nucleo EVA, Exterior EVA, 22mm, Redonda, 27 x 50 cm, 2023, peso 320g. Cor rosa e lima",
        price: 640.00,
        image: "adidas_bt_3_0_rosa_amarelo.jpg", 
        category: "Raquetes",
    },
    {
        id: 2,
        brand: "ADIDAS",
        title: "Raquete De Beach Tennis adidas Bt 3.0 Azul E Rosa",
        description: "Nucleo EVA, Exterior EVA, 22mm, Redonda, 27 x 50 cm, 2023, peso 320g. Cor Azul com Rosa",
        price: 640.00,
        image: "adidas_bt_3_0_azul_rosa.jpg", 
        category: "Raquetes",
    },
    {
        id: 3,
        brand: "ADIDAS",
        title: "Raquete De Beach Tennis adidas Rx 3.1 H14",
        description: "Nucleo EVA Soft, Exterior Fibra de Vidro, 22mm, Redonda, 27 x 50 cm, 2023, peso 330g. Verde/azul Cor Verde",
        price: 630.00,
        image: "adidas_rx_3_1_h14.jpg", 
        category: "Raquetes",
    },
    {
        id: 4,
        brand: "ADIDAS",
        title: "Raquete De Beach Tennis adidas Rx H14 Carbono 3k 2023",
        description: "Nucleo Carbono, Exterior Carbono com EVA, 22mm, Redonda, 27 x 50 cm, 2023, peso 320g Cor Verde Azul E Preto",
        price: 700.00,
        image: "adidas_rx_h14_carbono_3k.jpg", 
        category: "Raquetes",
    },
    {
        id: 5,
        brand: "ADIDAS",
        title: "Raquete De Beach Tennis adidas Bt 3.0 Azul/verde",
        description: "Nucleo Fibrade Vidro, Exterior Fibra de Vidro, 22mm, Redonda, 30 x 50 cm, 2023, peso 330g Cor Azul-turquesa",
        price: 640.00,
        image: "adidas_bt_3_0_azul_verde.jpg", 
        category: "Raquetes",
    },
    {
        id: 6,
        brand: "Speed Pró",
        title: "Raquete Beach Tennis 3k Carbono Speed Pro",
        description: "Nucleo EVA, Exterior Carbono 3K, 22mm, Redonda, 27 x 50 cm, 2023, peso 320g, 15 anos",
        price: 550.00,
        image: "speed_pro_3k_carbono.jpg", 
        category: "Raquetes",
    },
    {
        id: 7,
        brand: "Wilson",
        title: "Raquete De Beach Tennis Tryumph Wrbt04004005",
        description: "Nucleo Fibra de Vidro, Exterior Fibra de Vidro, 22mm, Redonda, 27 x 50 cm, 2023, peso 345g",
        price: 670.00,
        image: "wilson_tryumph.jpg", 
        category: "Raquetes",
    },
    {
        id: 8,
        brand: "Canewin",
        title: "Raquete De Pádel De Praia Camewin Raquete Beach Tennis 2022",
        description: "Nucleo Soft EVA, Exterior Carbono, 20mm, Redonda, 23 x 50 cm, 2023, peso 320g Cor Azul",
        price: 350.00,
        image: "canewin_2022_azul.jpg", 
        category: "Raquetes",
    },
    {
        id: 9,
        brand: "Canewin",
        title: "Raquete Beach Tennis Carbono Camewin Cores Modelos",
        description: "Nucleo Soft EVA, Exterior Fibra de Carbono, 20mm, Lagrima 33 x 48 cm, 2023, peso 330g, 8 anos",
        price: 340.00,
        image: "canewin_carbono_cores.jpg", 
        category: "Raquetes",
    },
    {
        id: 10,
        brand: "Seafront",
        title: "Raquete De Beach Tennis Seafront Venice Pro 3k",
        description: "3K Carbono, 22mm.",
        price: 360.00,
        image: "seafront_venice_pro_3k.jpg", 
        category: "Raquetes",
    },
    {
        id: 11,
        brand: "Sulina",
        title: "Raquetes De Beach Tennis Sulina",
        description: "Fibra de Maderira",
        price: 160.00,
        image: "sulina.jpg", 
        category: "Raquetes",
    },
    {
        id: 12,
        brand: "Pro Life",
        title: "Raquete Beach Tennis 100% Fibra Carbono 3k Prolife Original",
        description: "Nucleo Soft EVA, Exterior Fibra de Carbono, 22mm, Redonda, 23 x 50 cm, 2023, peso 330g",
        price: 560.00,
        image: "prolife_3k_original.jpg", 
        category: "Raquetes",
    },
    {
        id: 13,
        brand: "Pro Life",
        title: "Raquete Beach Tennis Pro Original Fibra Carbono Prolife",
        description: "Nucleo Soft EVA, Exterior Fibra de Carbono, 22mm, Redonda, 23 x 50 cm, 2023, peso 330g",
        price: 580.00,
        image: "prolife_carbono.jpg", 
        category: "Raquetes",
    },
    {
        id: 14,
        brand: "ODISSEI",
        title: "Bola Beach Tennis Pack 3 un.",
        description: "Bola para Beach Tennis, pacote com 3 unidades.",
        price: 42.00,
        image: "odissei_beach_tennis_balls.jpg", 
        category: "Bolas e Acessórios",
    },
    {
        id: 15,
        brand: "HEAD",
        title: "Bola De Beach Tennis Head - Pack 02 un.",
        description: "Bola para Beach Tennis, pacote com 2 unidades.",
        price: 70.00,
        image: "head_beach_tennis_balls.jpg", 
        category: "Bolas e Acessórios",
    },
    {
        id: 16,
        brand: "ADIDAS",
        title: "Bola Beach Tennis Aditour adidas Pack 3 un.",
        description: "Bola para Beach Tennis Aditour, pacote com 3 unidades.",
        price: 99.00,
        image: "adidas_beach_tennis_balls.jpg", 
        category: "Bolas e Acessórios",
    },
    {
        id: 17,
        brand: "Wilson",
        title: "Bola Beach Tennis Wilson Pack 3 un.",
        description: "Bola para Beach Tennis Wilson, pacote com 3 unidades.",
        price: 68.00,
        image: "wilson_beach_tennis_balls.jpg", 
        category: "Bolas e Acessórios",
    },
    {
        id: 18,
        brand: "Zarsia",
        title: "Grip",
        description: "Grip para raquete de Beach Tennis.",
        price: 15.00,
        image: "zarsia_grip.jpg", 
        category: "Acessórios",
    },
];